### ISSUE TITLE
Fail building gem windows7

### ISSUE THREAD

**Issue by stereobooster** [tmm1/perftools.rb#45]
```
D:/tools/ruby192/bin/ruby.exe extconf.rb 
NOTE: Gem.activate is deprecated, use Specification#activate. It will be removed on or after 2011-10-01.
Gem.activate called from extconf.rb:24.
(I'm about to compile google-perftools.. this will definitely take a while)
  -- tar zpxvf gperftools-2.0.tar.gz
  -- patch -p1 < ../../../patches/perftools.patch
  -- patch -p1 < ../../../patches/perftools-notests.patch
  -- patch -p1 < ../../../patches/perftools-pprof.patch
  -- patch -p1 < ../../../patches/perftools-gc.patch
  -- patch -p1 < ../../../patches/perftools-debug.patch
  -- patch -p1 < ../../../patches/perftools-objects.patch
  -- patch -p1 < ../../../patches/perftools-frames.patch
  -- patch -p1 < ../../../patches/perftools-realtime.patch
  -- sed -i -e 's,SpinLock,ISpinLock,g' src/*.cc src/*.h src/base/*.cc src/base/*.h
  -- ./configure --disable-heap-profiler --disable-heap-checker --disable-debugalloc --disable-shared
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=D:/tools/ruby192/bin/ruby
extconf.rb:6:in `sys': ./configure --disable-heap-profiler --disable-heap-checker --disable-debugalloc --disable-shared failed, please report to https://github.com/tmm1/perfools.rb/issues/new with D:/tools/ruby192/lib/ruby/gems/1.9.1/bundler/gems/perftools.rb-961890a077bd/ext/src/mkmf.log and D:/tools/ruby192/lib/ruby/gems/1.9.1/bundler/gems/perftools.rb-961890a077bd/ext/src/gperftools-2.0/config.log (RuntimeError)
    from extconf.rb:76:in `block (2 levels) in <main>'
    from extconf.rb:72:in `chdir'
    from extconf.rb:72:in `block in <main>'
    from extconf.rb:36:in `chdir'
    from extconf.rb:36:in `<main>'
```

```
"tar zpxvf gperftools-2.0.tar.gz"
gperftools-2.0/
gperftools-2.0/doc/
gperftools-2.0/doc/index.html
gperftools-2.0/doc/designstyle.css
gperftools-2.0/doc/pprof_remote_servers.html
gperftools-2.0/doc/tcmalloc.html
gperftools-2.0/doc/overview.gif
gperftools-2.0/doc/pageheap.gif
gperftools-2.0/doc/spanmap.gif
gperftools-2.0/doc/threadheap.gif
gperftools-2.0/doc/t-test1.times.txt
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.1024.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.128.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.131072.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.16384.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.2048.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.256.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.32768.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.4096.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.512.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.64.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.65536.bytes.png
gperftools-2.0/doc/tcmalloc-opspercpusec.vs.threads.8192.bytes.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.1.threads.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.12.threads.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.16.threads.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.2.threads.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.20.threads.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.3.threads.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.4.threads.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.5.threads.png
gperftools-2.0/doc/tcmalloc-opspersec.vs.size.8.threads.png
gperftools-2.0/doc/overview.dot
gperftools-2.0/doc/pageheap.dot
gperftools-2.0/doc/spanmap.dot
gperftools-2.0/doc/threadheap.dot
gperftools-2.0/doc/heapprofile.html
gperftools-2.0/doc/heap-example1.png
gperftools-2.0/doc/heap_checker.html
gperftools-2.0/doc/cpuprofile.html
gperftools-2.0/doc/cpuprofile-fileformat.html
gperftools-2.0/doc/pprof-test-big.gif
gperftools-2.0/doc/pprof-test.gif
gperftools-2.0/doc/pprof-vsnprintf-big.gif
gperftools-2.0/doc/pprof-vsnprintf.gif
gperftools-2.0/doc/pprof.1
gperftools-2.0/m4/
gperftools-2.0/m4/ac_have_attribute.m4
gperftools-2.0/m4/acx_nanosleep.m4
gperftools-2.0/m4/acx_pthread.m4
gperftools-2.0/m4/compiler_characteristics.m4
gperftools-2.0/m4/install_prefix.m4
gperftools-2.0/m4/libtool.m4
gperftools-2.0/m4/ltoptions.m4
gperftools-2.0/m4/ltsugar.m4
gperftools-2.0/m4/ltversion.m4
gperftools-2.0/m4/lt~obsolete.m4
gperftools-2.0/m4/namespaces.m4
gperftools-2.0/m4/pc_from_ucontext.m4
gperftools-2.0/m4/program_invocation_name.m4
gperftools-2.0/m4/stl_namespace.m4
gperftools-2.0/packages/
gperftools-2.0/packages/rpm/
gperftools-2.0/packages/rpm/rpm.spec
gperftools-2.0/packages/rpm.sh
gperftools-2.0/packages/deb.sh
gperftools-2.0/packages/deb/
gperftools-2.0/packages/deb/README
gperftools-2.0/packages/deb/compat
gperftools-2.0/packages/deb/control
gperftools-2.0/packages/deb/copyright
gperftools-2.0/packages/deb/docs
gperftools-2.0/packages/deb/rules
gperftools-2.0/packages/deb/changelog
gperftools-2.0/packages/deb/libgperftools-dev.dirs
gperftools-2.0/packages/deb/libgperftools-dev.install
gperftools-2.0/packages/deb/libgperftools0.dirs
gperftools-2.0/packages/deb/libgperftools0.install
gperftools-2.0/packages/deb/libgperftools0.manpages
gperftools-2.0/src/
gperftools-2.0/src/base/
gperftools-2.0/src/base/logging.cc
gperftools-2.0/src/base/dynamic_annotations.c
gperftools-2.0/src/base/logging.h
gperftools-2.0/src/base/commandlineflags.h
gperftools-2.0/src/base/basictypes.h
gperftools-2.0/src/base/dynamic_annotations.h
gperftools-2.0/src/base/googleinit.h
gperftools-2.0/src/base/simple_mutex.h
gperftools-2.0/src/base/sysinfo.h
gperftools-2.0/src/base/spinlock.h
gperftools-2.0/src/base/spinlock_internal.h
gperftools-2.0/src/base/atomicops.h
gperftools-2.0/src/base/atomicops-internals-macosx.h
gperftools-2.0/src/base/atomicops-internals-linuxppc.h
gperftools-2.0/src/base/atomicops-internals-windows.h
gperftools-2.0/src/base/atomicops-internals-x86.h
gperftools-2.0/src/base/spinlock_win32-inl.h
gperftools-2.0/src/base/spinlock_linux-inl.h
gperftools-2.0/src/base/spinlock_posix-inl.h
gperftools-2.0/src/base/synchronization_profiling.h
gperftools-2.0/src/base/atomicops-internals-arm-generic.h
gperftools-2.0/src/base/atomicops-internals-arm-v6plus.h
gperftools-2.0/src/base/spinlock.cc
gperftools-2.0/src/base/spinlock_internal.cc
gperftools-2.0/src/base/atomicops-internals-x86.cc
gperftools-2.0/src/base/elf_mem_image.cc
gperftools-2.0/src/base/vdso_support.cc
gperftools-2.0/src/base/elf_mem_image.h
gperftools-2.0/src/base/vdso_support.h
gperftools-2.0/src/base/sysinfo.cc
gperftools-2.0/src/base/cycleclock.h
gperftools-2.0/src/base/arm_instruction_set_select.h
gperftools-2.0/src/base/thread_annotations.h
gperftools-2.0/src/base/elfcore.h
gperftools-2.0/src/base/linux_syscall_support.h
gperftools-2.0/src/base/linuxthreads.h
gperftools-2.0/src/base/stl_allocator.h
gperftools-2.0/src/base/thread_lister.h
gperftools-2.0/src/base/thread_lister.c
gperftools-2.0/src/base/linuxthreads.cc
gperftools-2.0/src/base/low_level_alloc.cc
gperftools-2.0/src/base/low_level_alloc.h
gperftools-2.0/src/google/
gperftools-2.0/src/google/heap-checker.h
gperftools-2.0/src/google/heap-profiler.h
gperftools-2.0/src/google/malloc_extension.h
gperftools-2.0/src/google/malloc_extension_c.h
gperftools-2.0/src/google/malloc_hook.h
gperftools-2.0/src/google/malloc_hook_c.h
gperftools-2.0/src/google/profiler.h
gperftools-2.0/src/google/stacktrace.h
gperftools-2.0/src/google/tcmalloc.h
gperftools-2.0/src/gperftools/
gperftools-2.0/src/gperftools/stacktrace.h
gperftools-2.0/src/gperftools/malloc_hook.h
gperftools-2.0/src/gperftools/malloc_hook_c.h
gperftools-2.0/src/gperftools/malloc_extension.h
gperftools-2.0/src/gperftools/malloc_extension_c.h
gperftools-2.0/src/gperftools/heap-profiler.h
gperftools-2.0/src/gperftools/heap-checker.h
gperftools-2.0/src/gperftools/profiler.h
gperftools-2.0/src/gperftools/tcmalloc.h.in
gperftools-2.0/src/solaris/
gperftools-2.0/src/solaris/libstdc++.la
gperftools-2.0/src/tests/
gperftools-2.0/src/tests/addressmap_unittest.cc
gperftools-2.0/src/tests/atomicops_unittest.cc
gperftools-2.0/src/tests/current_allocated_bytes_test.cc
gperftools-2.0/src/tests/debugallocation_test.cc
gperftools-2.0/src/tests/debugallocation_test.sh
gperftools-2.0/src/tests/frag_unittest.cc
gperftools-2.0/src/tests/getpc_test.cc
gperftools-2.0/src/tests/heap-checker-death_unittest.sh
gperftools-2.0/src/tests/heap-checker_unittest.cc
gperftools-2.0/src/tests/heap-checker_unittest.sh
gperftools-2.0/src/tests/heap-profiler_unittest.cc
gperftools-2.0/src/tests/heap-profiler_unittest.sh
gperftools-2.0/src/tests/low_level_alloc_unittest.cc
gperftools-2.0/src/tests/malloc_extension_c_test.c
gperftools-2.0/src/tests/malloc_extension_test.cc
gperftools-2.0/src/tests/malloc_hook_test.cc
gperftools-2.0/src/tests/testutil.h
gperftools-2.0/src/tests/testutil.cc
gperftools-2.0/src/tests/markidle_unittest.cc
gperftools-2.0/src/tests/maybe_threads_unittest.sh
gperftools-2.0/src/tests/memalign_unittest.cc
gperftools-2.0/src/tests/packed-cache_test.cc
gperftools-2.0/src/tests/page_heap_test.cc
gperftools-2.0/src/tests/pagemap_unittest.cc
gperftools-2.0/src/tests/profile-handler_unittest.cc
gperftools-2.0/src/tests/profiledata_unittest.cc
gperftools-2.0/src/tests/profiler_unittest.cc
gperftools-2.0/src/tests/profiler_unittest.sh
gperftools-2.0/src/tests/raw_printer_test.cc
gperftools-2.0/src/tests/realloc_unittest.cc
gperftools-2.0/src/tests/sampler_test.cc
gperftools-2.0/src/tests/sampling_test.cc
gperftools-2.0/src/tests/sampling_test.sh
gperftools-2.0/src/tests/simple_compat_test.cc
gperftools-2.0/src/tests/stack_trace_table_test.cc
gperftools-2.0/src/tests/stacktrace_unittest.cc
gperftools-2.0/src/tests/system-alloc_unittest.cc
gperftools-2.0/src/tests/tcmalloc_unittest.cc
gperftools-2.0/src/tests/tcmalloc_large_unittest.cc
gperftools-2.0/src/tests/thread_dealloc_unittest.cc
gperftools-2.0/src/third_party/
gperftools-2.0/src/third_party/valgrind.h
gperftools-2.0/src/windows/
gperftools-2.0/src/windows/google/
gperftools-2.0/src/windows/google/tcmalloc.h
gperftools-2.0/src/windows/gperftools/
gperftools-2.0/src/windows/gperftools/tcmalloc.h.in
gperftools-2.0/src/windows/gperftools/tcmalloc.h
gperftools-2.0/src/windows/port.h
gperftools-2.0/src/windows/mingw.h
gperftools-2.0/src/windows/mini_disassembler.h
gperftools-2.0/src/windows/mini_disassembler_types.h
gperftools-2.0/src/windows/preamble_patcher.h
gperftools-2.0/src/windows/port.cc
gperftools-2.0/src/windows/ia32_modrm_map.cc
gperftools-2.0/src/windows/ia32_opcode_map.cc
gperftools-2.0/src/windows/mini_disassembler.cc
gperftools-2.0/src/windows/patch_functions.cc
gperftools-2.0/src/windows/preamble_patcher.cc
gperftools-2.0/src/windows/preamble_patcher_with_stub.cc
gperftools-2.0/src/windows/get_mangled_names.cc
gperftools-2.0/src/windows/override_functions.cc
gperftools-2.0/src/windows/config.h
gperftools-2.0/src/windows/preamble_patcher_test.cc
gperftools-2.0/src/windows/shortproc.asm
gperftools-2.0/src/windows/auto_testing_hook.h
gperftools-2.0/src/windows/nm-pdb.c
gperftools-2.0/src/windows/addr2line-pdb.c
gperftools-2.0/src/config.h.in
gperftools-2.0/src/profiler.cc
gperftools-2.0/src/profile-handler.cc
gperftools-2.0/src/profiledata.cc
gperftools-2.0/src/profiledata.h
gperftools-2.0/src/profile-handler.h
gperftools-2.0/src/getpc.h
gperftools-2.0/src/stacktrace.cc
gperftools-2.0/src/stacktrace_config.h
gperftools-2.0/src/stacktrace_generic-inl.h
gperftools-2.0/src/stacktrace_libunwind-inl.h
gperftools-2.0/src/stacktrace_arm-inl.h
gperftools-2.0/src/stacktrace_powerpc-inl.h
gperftools-2.0/src/stacktrace_x86-inl.h
gperftools-2.0/src/stacktrace_win32-inl.h
gperftools-2.0/src/tcmalloc.cc
gperftools-2.0/src/common.h
gperftools-2.0/src/internal_logging.h
gperftools-2.0/src/system-alloc.h
gperftools-2.0/src/packed-cache-inl.h
gperftools-2.0/src/tcmalloc_guard.h
gperftools-2.0/src/pagemap.h
gperftools-2.0/src/sampler.h
gperftools-2.0/src/central_freelist.h
gperftools-2.0/src/linked_list.h
gperftools-2.0/src/libc_override.h
gperftools-2.0/src/libc_override_gcc_and_weak.h
gperftools-2.0/src/libc_override_glibc.h
gperftools-2.0/src/libc_override_osx.h
gperftools-2.0/src/libc_override_redefine.h
gperftools-2.0/src/page_heap.h
gperftools-2.0/src/page_heap_allocator.h
gperftools-2.0/src/span.h
gperftools-2.0/src/static_vars.h
gperftools-2.0/src/symbolize.h
gperftools-2.0/src/thread_cache.h
gperftools-2.0/src/stack_trace_table.h
gperftools-2.0/src/malloc_hook-inl.h
gperftools-2.0/src/malloc_hook_mmap_linux.h
gperftools-2.0/src/malloc_hook_mmap_freebsd.h
gperftools-2.0/src/maybe_threads.h
gperftools-2.0/src/addressmap-inl.h
gperftools-2.0/src/raw_printer.h
gperftools-2.0/src/heap-profile-table.h
gperftools-2.0/src/heap-checker.cc
gperftools-2.0/src/heap-checker-bcad.cc
gperftools-2.0/src/debugallocation.cc
gperftools-2.0/src/common.cc
gperftools-2.0/src/internal_logging.cc
gperftools-2.0/src/system-alloc.cc
gperftools-2.0/src/memfs_malloc.cc
gperftools-2.0/src/central_freelist.cc
gperftools-2.0/src/page_heap.cc
gperftools-2.0/src/sampler.cc
gperftools-2.0/src/span.cc
gperftools-2.0/src/stack_trace_table.cc
gperftools-2.0/src/static_vars.cc
gperftools-2.0/src/symbolize.cc
gperftools-2.0/src/thread_cache.cc
gperftools-2.0/src/malloc_hook.cc
gperftools-2.0/src/malloc_extension.cc
gperftools-2.0/src/maybe_threads.cc
gperftools-2.0/src/heap-profile-table.cc
gperftools-2.0/src/heap-profiler.cc
gperftools-2.0/src/raw_printer.cc
gperftools-2.0/src/memory_region_map.cc
gperftools-2.0/src/config_for_unittests.h
gperftools-2.0/src/memory_region_map.h
gperftools-2.0/src/tcmalloc.h
gperftools-2.0/src/pprof
gperftools-2.0/vsprojects/
gperftools-2.0/vsprojects/addr2line-pdb/
gperftools-2.0/vsprojects/addr2line-pdb/addr2line-pdb.vcproj
gperftools-2.0/vsprojects/addressmap_unittest/
gperftools-2.0/vsprojects/addressmap_unittest/addressmap_unittest.vcproj
gperftools-2.0/vsprojects/current_allocated_bytes_test/
gperftools-2.0/vsprojects/current_allocated_bytes_test/current_allocated_bytes_test.vcproj
gperftools-2.0/vsprojects/frag_unittest/
gperftools-2.0/vsprojects/frag_unittest/frag_unittest.vcproj
gperftools-2.0/vsprojects/libtcmalloc_minimal/
gperftools-2.0/vsprojects/libtcmalloc_minimal/libtcmalloc_minimal.vcproj
gperftools-2.0/vsprojects/low_level_alloc_unittest/
gperftools-2.0/vsprojects/low_level_alloc_unittest/low_level_alloc_unittest.vcproj
gperftools-2.0/vsprojects/malloc_extension_test/
gperftools-2.0/vsprojects/malloc_extension_test/malloc_extension_test.vcproj
gperftools-2.0/vsprojects/malloc_hook_test/
gperftools-2.0/vsprojects/malloc_hook_test/malloc_hook_test.vcproj
gperftools-2.0/vsprojects/markidle_unittest/
gperftools-2.0/vsprojects/markidle_unittest/markidle_unittest.vcproj
gperftools-2.0/vsprojects/nm-pdb/
gperftools-2.0/vsprojects/nm-pdb/nm-pdb.vcproj
gperftools-2.0/vsprojects/packed-cache_test/
gperftools-2.0/vsprojects/packed-cache_test/packed-cache_test.vcproj
gperftools-2.0/vsprojects/page_heap_test/
gperftools-2.0/vsprojects/page_heap_test/page_heap_test.vcproj
gperftools-2.0/vsprojects/pagemap_unittest/
gperftools-2.0/vsprojects/pagemap_unittest/pagemap_unittest.vcproj
gperftools-2.0/vsprojects/preamble_patcher_test/
gperftools-2.0/vsprojects/preamble_patcher_test/preamble_patcher_test.vcproj
gperftools-2.0/vsprojects/realloc_unittest/
gperftools-2.0/vsprojects/realloc_unittest/realloc_unittest.vcproj
gperftools-2.0/vsprojects/sampler_test/
gperftools-2.0/vsprojects/sampler_test/sampler_test.vcproj
gperftools-2.0/vsprojects/stack_trace_table_test/
gperftools-2.0/vsprojects/stack_trace_table_test/stack_trace_table_test.vcproj
gperftools-2.0/vsprojects/tcmalloc_minimal_large/
gperftools-2.0/vsprojects/tcmalloc_minimal_large/tcmalloc_minimal_large_unittest.vcproj
gperftools-2.0/vsprojects/tcmalloc_minimal_unittest/
gperftools-2.0/vsprojects/tcmalloc_minimal_unittest/tcmalloc_minimal_unittest.vcproj
gperftools-2.0/vsprojects/thread_dealloc_unittest/
gperftools-2.0/vsprojects/thread_dealloc_unittest/thread_dealloc_unittest.vcproj
gperftools-2.0/vsprojects/tmu-static/
gperftools-2.0/vsprojects/tmu-static/tmu-static.vcproj
gperftools-2.0/README
gperftools-2.0/configure.ac
gperftools-2.0/aclocal.m4
gperftools-2.0/AUTHORS
gperftools-2.0/COPYING
gperftools-2.0/ChangeLog
gperftools-2.0/INSTALL
gperftools-2.0/NEWS
gperftools-2.0/README_windows.txt
gperftools-2.0/TODO
gperftools-2.0/Makefile.am
gperftools-2.0/Makefile.in
gperftools-2.0/configure
gperftools-2.0/compile
gperftools-2.0/config.guess
gperftools-2.0/config.sub
gperftools-2.0/depcomp
gperftools-2.0/install-sh
gperftools-2.0/ltmain.sh
gperftools-2.0/missing
gperftools-2.0/mkinstalldirs
gperftools-2.0/libtool
gperftools-2.0/gperftools.sln
"patch -p1 < ../../../patches/perftools.patch"
patching file `Makefile.in'
Hunk #1 succeeded at 1738 (offset 371 lines).
patching file `src/profile-handler.cc'
Hunk #1 succeeded at 293 with fuzz 2 (offset 29 lines).
patching file `src/profiledata.cc'
patching file `src/profiledata.h'
patching file `src/profiler.cc'
Hunk #1 succeeded at 68 (offset 5 lines).
Hunk #3 succeeded at 288 (offset 5 lines).
patching file `src/stacktrace.cc'
Hunk #1 succeeded at 52 with fuzz 2.
Hunk #2 succeeded at 109 (offset 39 lines).
"patch -p1 < ../../../patches/perftools-notests.patch"
patching file `Makefile.in'
"patch -p1 < ../../../patches/perftools-pprof.patch"
patching file `src/pprof'
Hunk #1 succeeded at 581 (offset 21 lines).
Hunk #3 succeeded at 2892 (offset 455 lines).
Hunk #5 succeeded at 2930 (offset 455 lines).
Hunk #6 succeeded at 3407 (offset 29 lines).
"patch -p1 < ../../../patches/perftools-gc.patch"
patching file `src/profiledata.cc'
patching file `src/profiledata.h'
patching file `src/profiler.cc'
Hunk #1 succeeded at 92 (offset 5 lines).
Hunk #3 succeeded at 319 (offset 5 lines).
"patch -p1 < ../../../patches/perftools-debug.patch"
patching file `Makefile.in'
Hunk #1 succeeded at 1720 (offset 353 lines).
"patch -p1 < ../../../patches/perftools-objects.patch"
patching file `src/profile-handler.cc'
patching file `src/profiler.cc'
"patch -p1 < ../../../patches/perftools-frames.patch"
patching file `src/profiledata.h'
"patch -p1 < ../../../patches/perftools-realtime.patch"
patching file `src/profile-handler.cc'
"sed -i -e 's,SpinLock,ISpinLock,g' src/*.cc src/*.h src/base/*.cc src/base/*.h"
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
sed: preserving permissions for `src/base/sed004612': Permission denied
"./configure --disable-heap-profiler --disable-heap-checker --disable-debugalloc --disable-shared"
```

**Comment by thomthom** [comment]
@stereobooster I see you closed the issue. Did you find a solution?

**Comment by stereobooster** [comment]
@thomthom kind of - I do not use windows. Joking. I closed all old inactive issues to clean up my list of issues in Github
