### ISSUE TITLE
Problems with installing latest perftools.rb 2.0.4 on Mac OS 10.11 with Ruby 2.2.2

### ISSUE THREAD

**Issue by emilpetkov** [tmm1/perftools.rb#77]
Hi

I am trying to install the latest perftools.rb on Mac OS 10.11 (El Capitan) with Ruby 2.2.2 and getting following errors:
```
  0 /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20151225-33051-19s3dkx.rb extconf.rb
  1 (I'm about to compile google-perftools.. this will definitely take a while)
  2   -- tar zpxvf gperftools-2.0.tar.gz
  3   -- patch -p1 < ../../../patches/perftools.patch
  4   -- patch -p1 < ../../../patches/perftools-notests.patch
  5   -- patch -p1 < ../../../patches/perftools-pprof.patch
  6   -- patch -p1 < ../../../patches/perftools-gc.patch
  7   -- patch -p1 < ../../../patches/perftools-debug.patch
  8   -- patch -p1 < ../../../patches/perftools-objects.patch
  9   -- patch -p1 < ../../../patches/perftools-frames.patch
 10   -- patch -p1 < ../../../patches/perftools-realtime.patch
 11   -- patch -p1 < ../../../patches/perftools-pause.patch
 12   -- sed -i -e 's,SpinLock,ISpinLock,g' src/*.cc src/*.h src/base/*.cc src/base/*.h
 13   -- ./configure --disable-heap-profiler --disable-heap-checker --disable-debugalloc --disable-shared
 14   -- make
 15 checking for method.h... *** extconf.rb failed ***
 16 Could not create Makefile due to some reason, probably lack of necessary
 17 libraries and/or headers.  Check the mkmf.log file for more details.  You may
 18 need configuration options.
 19
 20 Provided configuration options:
 21   --with-opt-dir
 22   --without-opt-dir
 23   --with-opt-include
 24   --without-opt-include=${opt-dir}/include
 25   --with-opt-lib
 26   --without-opt-lib=${opt-dir}/lib
 27   --with-make-prog
 28   --without-make-prog
 29   --srcdir=.
 30   --curdir
 31   --ruby=/Users/emilpetkov/.rvm/rubies/ruby-2.2.2/bin/$(RUBY_BASE_NAME)
 32 /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
 33 You have to install development tools first.
 34   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
 35   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
 36   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
 37   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
 38   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:321:in `open'
 39   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
 40   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:321:in `open'
 41   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
 42   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
 43   from /Users/emilpetkov/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
 44   from extconf.rb:117:in `block in <main>'
 45   from /Users/emilpetkov/.rvm/gems/ruby-2.2.2/gems/debase-ruby_core_source-0.8.4/lib/debase/ruby_core_source.rb:12:in `call'
 46   from /Users/emilpetkov/.rvm/gems/ruby-2.2.2/gems/debase-ruby_core_source-0.8.4/lib/debase/ruby_core_source.rb:12:in `create_makefile_with_core'
 47   from extconf.rb:126:in `<main>'
 48
 49 extconf failed, exit code 1
```

**Comment by emilpetkov** [comment]
XCode 7.2 + command line tools installed. 2.0.4 successfully installs on same env with ruby 2.1.0.
